name: Setup environment

inputs:
  cache:
    description: Enable caching
    default: 'true'
  node:
    description: The Node.js version to install
    required: true
  solana:
    description: The Solana version to install

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Install Rust
      uses: metaplex-foundation/actions/install-rust@v1
      with:
        toolchain: stable
        components: clippy,rustfmt
    - name: Install Rust Nightly
      uses: metaplex-foundation/actions/install-rust@v1
      with:
        toolchain: nightly
        components: clippy,rustfmt
    - name: Install Solana
      if: ${{ inputs.solana != '' }}
      uses: metaplex-foundation/actions/install-solana@v1
      with:
        version: ${{ inputs.solana }}
        cache: ${{ inputs.cache }}
